### frontend.yaml
# Contains the Web Frontend for the Shiny Sorter.
###
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend-config
data:
  app.config.json: |
    {
      "queryServerAddress": "{{ .Values.queryServer.prefix }}/query",
      "supabaseAddress": "http://{{ .Values.supabase.address }}:{{ .Values.supabase.kong.port }}",
      "supabaseKey": "{{ .Values.supabase.anonKey }}"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      {{ with .Values.frontend }}
      {{ if .nodeSelector }}
      nodeSelector:
        {{- toYaml .nodeSelector | nindent 8}}
      {{ end }}
      {{ if .tolerations }}
      tolerations:
        {{- toYaml .tolerations | nindent 8}}
      {{ end }}
      {{ end }}
      terminationGracePeriodSeconds: 5
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: Always
        env:
        - name: TARGET_BASE_PATH
          value: {{ trimPrefix "/" .Values.frontend.prefix }}
        ports:
        - name: ui
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/html/assets
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "shinysorter.fullname" . }}-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
spec:
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shinysorter.fullname" . }}-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/{{ .Values.frontend.prefix }})$ $1/ redirect;
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.frontend.prefix }}/?
        pathType: Prefix
        backend:
          service:
            name: {{ include "shinysorter.fullname" . }}-frontend
            port:
              number: 80