apiVersion: v1
kind: Secret
metadata:
  name: supabase-migrations
data:
{{- $root := . -}}
{{- range $path, $bytes := .Files.Glob "supabase-migrations/*.sql" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
{{- end }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: supabase-migration-init
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command:  ["sh", "-c", "until nc -w 5 -z supabase-postgres {{ .Values.supabase.postgresql.port }} > /dev/null; do echo Waiting for postgres.; sleep 2; done; echo 'PostgreSQL is up'"]
      containers:
      - name: pgclient
        image: codingpuss/postgres-client
        command: ["sh", "-c", "for f in /migrations/*; do psql $PG_CONNECTION_STRING -f /migrations/$(basename $f); done"]
        env:
        - name: PG_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: supabase-db-credentials
              key: connectionString
              optional: false
        volumeMounts:
        - name: migrations
          mountPath: /migrations
          readOnly: true
      volumes:
        - name: migrations
          secret:
            secretName: supabase-migrations
      restartPolicy: OnFailure
  backoffLimit: 4