apiVersion: v1
kind: Secret
metadata:
  name: supabase-db-credentials
stringData:
  connectionString: postgresql://postgres:{{ .Values.supabase.postgresql.password }}@{{ .Values.supabase.postgresql.address }}:{{ .Values.supabase.postgresql.port }}/postgres
  postgresPassword: {{ .Values.supabase.postgresql.password | default "postgresql.password not provided" }}
  supabaseAddress: "http://{{ .Values.supabase.address }}:3000"
  supabaseKey: "{{ .Values.supabase.anonKey | default "supabaseKey not provided"}}"
