### storage.yaml
# Contains the storage definitions for the project. Powered by Portworx, but
# can work with anything providing ReadWriteMany capabilities
###
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-importdir-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
reclaimPolicy: {{ .Values.reclaimPolicy }}
parameters:
  repl: "1"
  sharedv4: "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-importdir
  labels:
    meta.helm.sh/release-name: {{ include "shinysorter.fullname" . }}
  annotations:
  {{- toYaml .Values.importer.storage.pvcAnnotations | nindent 4 }}
spec:
  storageClassName: {{ .Values.importer.storage.storageClassName | default "shinysorter-importdir-sc" }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-supastoragedir-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
reclaimPolicy: {{ .Values.reclaimPolicy }}
parameters:
  repl: "1"
  fs: "ext4"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-supastoragedir
  labels:
    meta.helm.sh/release-name: {{ include "shinysorter.fullname" . }}
  annotations:
  {{- toYaml .Values.supabase.storage.storage.pvcAnnotations | nindent 4 }}
spec:
  storageClassName: {{ .Values.supabase.storage.storage.storageClassName | default "shinysorter-supastoragedir-sc" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shinysorter-supabase-postgres-data-sc
  annotations:
    helm.sh/hook: pre-install
provisioner: pxd.portworx.com
reclaimPolicy: {{ .Values.reclaimPolicy }}
parameters:
  repl: "1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shinysorter-supabase-postgres-data
  labels:
    meta.helm.sh/release-name: {{ include "shinysorter.fullname" . }}
  annotations:
  {{- toYaml .Values.supabase.postgresql.storage.pvcAnnotations | nindent 4 }}
spec:
  storageClassName: {{ .Values.supabase.postgresql.storage.storageClassName | default "shinysorter-supabase-postgres-data-sc" }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi