reclaimPolicy: Retain

deploymentAddress: ""

webdav:
  nameOverride: "shinysorter-importdir-webdav"
  urls:
    /:
    - user: username
      password:
  service:
    type: LoadBalancer
    port: 80
  persistence:
    enabled: true
    type: pvc
    existingClaim: shinysorter-importdir

importer:
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-importer"
  tag: "alpha-v0.4.0"
  importSubdirectory: ""
  nodeSelector: null
  tolerations: null
  storage:
    pvcAnnotations: {}
    storageClassName: null

frontend:
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-frontend"
  tag: "alpha-v0.4.0"
  prefix: "ui"
  nodeSelector: null
  tolerations: null

queryServer:
  port: 3268
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-queryserver"
  tag: "alpha-v0.4.0"
  prefix: "query"
  nodeSelector: null
  tolerations: null

backup:
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-backuptool"
  tag: "alpha-v0.4.0"

supabase:
  jwtSecret: ""
  anonKey: ""
  serviceKey: ""
  postgresql:
    address: ""
    password: ""
    port: 31415
    nodeSelector: null
    tolerations: null
    storage:
      pvcAnnotations: {}
      storageClassName: null
  studio:
    port: 3000
    nodeSelector: null
    tolerations: null
  rest:
    nodeSelector: null
    tolerations: null
  auth:
    nodeSelector: null
    tolerations: null
  realtime:
    nodeSelector: null
    tolerations: null
  storage:
    nodeSelector: null
    tolerations: null
    storage:
      pvcAnnotations: {}
      storageClassName: null
  meta:
    nodeSelector: null
    tolerations: null
  kong:
    port: 8000
    nodeSelector: null
    tolerations: null
