reclaimPolicy: Retain

deploymentAddress: ""

webdav:
  nameOverride: "shinysorter-importdir-webdav"
  urls:
    /:
    - user: username
      password:
  service:
    type: LoadBalancer
    port: 80
  persistence:
    enabled: true
    type: pvc
    existingClaim: shinysorter-importdir
  resources:
    limits:
      # No CPU limit
      memory: 1Gi # Handling file uploads, set a bigger memory limit in case
    requests:
      cpu: 10m
      memory: 50Mi

importer:
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-importer"
  tag: "alpha-v0.4.1"
  importSubdirectory: ""
  nodeSelector: null
  tolerations: null
  storage:
    pvcAnnotations: {}
    storageClassName: null
  resources:
    limits:
      # No CPU limit
      memory: 2Gi # Expect this to be relatively high as it's reading file contents into memory
    requests:
      cpu: 50m
      memory: 500Mi

frontend:
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-frontend"
  tag: "alpha-v0.4.1"
  prefix: "ui"
  nodeSelector: null
  tolerations: null
  resources:
    limits:
      # No CPU limit
      memory: 250Mi
    requests:
      cpu: 10m
      memory: 100Mi

queryServer:
  port: 3268
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-queryserver"
  tag: "alpha-v0.4.1"
  prefix: "query"
  nodeSelector: null
  tolerations: null
  resources:
    limits:
      # No CPU limit
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 500Mi

backup:
  image: "registry.home.crowhop.tech:8080/shinysorter/shinysorter-backuptool"
  tag: "alpha-v0.4.1"

supabase:
  jwtSecret: ""
  anonKey: ""
  serviceKey: ""
  postgresql:
    address: ""
    password: ""
    port: 31415
    nodeSelector: null
    tolerations: null
    storage:
      pvcAnnotations: {}
      storageClassName: null
    resources:
      limits:
        # No CPU limit
        memory: 1Gi # Set high memory limit to ensure indices have space in memory
      requests:
        cpu: 250m # Set high CPU request to ensure queries go fast
        memory: 250Mi
  studio:
    port: 3000
    nodeSelector: null
    tolerations: null
    resources:
      limits:
        # No CPU limit
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 250Mi
  rest:
    nodeSelector: null
    tolerations: null
    resources:
      limits:
        # No CPU limit
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 50Mi
  auth:
    nodeSelector: null
    tolerations: null
    resources:
      limits:
        # No CPU limit
        memory: 250Mi
      requests:
        cpu: 10m
        memory: 50Mi
  realtime:
    nodeSelector: null
    tolerations: null
    resources:
      limits:
        # No CPU limit
        memory: 500Mi
      requests:
        cpu: 50m
        memory: 100Mi
  storage:
    nodeSelector: null
    tolerations: null
    storage:
      pvcAnnotations: {}
      storageClassName: null
    resources:
      limits:
        # No CPU limit
        memory: 1Gi # Expect this to be relatively high as it's dealing with file contents
      requests:
        cpu: 50m # Set this relatively high to ensure we can serve file contents quickly
        memory: 500Mi
  meta:
    nodeSelector: null
    tolerations: null
    resources:
      limits:
        # No CPU limit
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 100Mi
  kong:
    port: 8000
    nodeSelector: null
    tolerations: null
    resources:
      limits:
        # No CPU limit
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 500Mi
