---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-conf
data:
  httpd.conf: |-
{{ tpl .Values.httpd_conf . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: htpasswd
data:
  {{- range $path, $users := .Values.urls }}
  {{ $path | replace "/" "" | default "-" }}: |-
      {{ range $user := $users }}
      {{- htpasswd $user.user $user.password }}
      {{ end }}
  {{- end }}

