apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "webdav.fullname" . }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - {{ if .Values.ingress.host }}host: {{.Values.ingress.host}} {{ end }}
    http:
      paths:
      - pathType: Prefix
        path: /{{ if .Values.ingress.path }}{{.Values.ingress.path}}{{ end }}
        backend:
          service:
            name: {{ include "webdav.fullname" . }}
            port:
              number: 80